name: Build UEFI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

            - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            pip \
            git \
            mono-devel \
            build-essential \
            lld \
            uuid-dev \
            nasm \
            gcc-aarch64-linux-gnu \
            python3 \
            python3-git \
            python3-pip \
            gettext \
            locales \
            gnupg \
            ca-certificates \
            clang \
            llvm \
            curl

          python3 -m pip install -r pip-requirements.txt --break-system-packages

      - name: Build
        run: |
          python3 build_uefi.py -d nio

      - name: Show build output
        run: |
          find . -type f \( -name "*.img" -o -name "*.efi" -o -name "*.fd" \) -print

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: nio-uefi
          path: |
            **/*.img
            **/*.efi
            **/*.fd
          if-no-files-found: error
